### ISSUE TITLE
Router middleware clobbers uuid

### ISSUE THREAD

**Issue by varnerac** [CrowdHailer/raxx#107]
The `uuid` dependency in the Request ID middleware clobbers my deps that use the Erlang uuid library.

https://hex.pm/packages/uuid_erl

**Comment by CrowdHailer** [comment]
My plan was always to remove the UUID dependency because I thought the RequestID middleware belonged in it's own repo. https://github.com/CrowdHailer/raxx/blob/master/mix.exs#L29

Just didn't think it would cause problems so quickly. 

Can you solve this with some kind of `override: true` or force in the the dependency declaration. If not the only solution is to get on to extracting RequestID to another project

**Comment by varnerac** [comment]
I don't think I can fix it that way. When Mix tries to compile the middleware, it won't find  `UUID.uuid4()` called https://github.com/CrowdHailer/raxx/blob/master/lib/raxx/request_id.ex#L56

I've hit this before, having to use the Erlang module in other Elixir code. Known issue: https://github.com/elixir-lang/elixir/issues/5232

**Comment by CrowdHailer** [comment]
Well I was going to move out some of the middleare at 1.0 release but we could move it up

**Comment by CrowdHailer** [comment]
This should be resolved. will get a new release to hex today
