### ISSUE TITLE
Add middleware example

### ISSUE THREAD

**Issue by lpil** [CrowdHailer/raxx#90]
There's a lot of issues suggesting some useful sounding middleware, but there is no example of what the middleware format it and how the user composes them together.

Could you add an example so that we can start contributing middlewares? :)

**Comment by CrowdHailer** [comment]
There is still some flexibility about how middleware is defined. I have some idea's but not 100% sure what is the best solution, because the implementation of checking some request headers may be very different to counting the number of response chunks. For that reason I have deliberately avoided setting up a middleware framework.

That said if you are not interested in streaming then you can follow this guide. https://github.com/CrowdHailer/Tokumei/blob/master/guides/writing-middleware-with-macros.md

I believe @samphilipd has written some middleware that just  works with handle_request?

**Comment by CrowdHailer** [comment]
@lpil is the logger example enough to be working with https://github.com/CrowdHailer/raxx/blob/master/lib/raxx/logger.ex
